### ISSUE TITLE
把项目在安卓系统8.0手机上运行项目崩溃

### ISSUE THREAD

**Issue by qiaoscong** [SpikeKing/wcl-video-list-demo#2]
java.lang.RuntimeException: this should be called in Main Thread
                                                       at com.volokh.danylo.video_player_manager.ui.MediaPlayerWrapper.onVideoSizeChanged(MediaPlayerWrapper.java:214)
                                                       at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3289)
                                                       at android.os.Handler.dispatchMessage(Handler.java:106)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
有时间您可以看一下

**Comment by baiseng** [comment]
问题 +1

**Comment by baiseng** [comment]
> 问题 +1

Android8.0 闪退
